// apps/blog/web-svelte/src/routes/posts/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { PageProps } from './$types';
  import { css } from '../../../styled-system/css';
  import Rail from '$lib/components/Rail.svelte';
  import Seo from '$lib/components/Seo.svelte';
  import ArchiveRow from '$lib/components/archive/ArchiveRow.svelte';
  import PostsArchive from '$lib/components/archive/PostsArchive.svelte';

  const { data }: PageProps = $props();

  const description = $derived(
    `${data.site.name}에 쓴 글 ${data.posts.length}편의 목록입니다. 번들러 구조, TypeScript 도메인 설계, React 패턴, 오픈소스 기여 경험을 다루며, 각 글은 직접 짠 코드와 실제로 부딪힌 문제를 함께 담고 있습니다.`,
  );

  /**
   * 필터 상태는 주소의 쿼리에서 오는데, 프리렌더에서는 그것을 읽을 수 없다
   * (SvelteKit이 `url.searchParams` 접근을 던진다 — 정적 파일 하나가 모든
   * 쿼리를 대표할 수 없다는 뜻이다). 그래서 산출물에는 **필터 없는 목록**이
   * 구워지고, 마운트 후에 인터랙티브 뷰로 갈린다.
   *
   * 그 폴백이 스피너가 아니라 글 목록인 것이 중요하다 — 아카이브 허브의
   * 내부 링크가 0개가 되면 크롤러가 글에 닿는 길이 하나 사라진다. React 판도
   * 같은 이유로 Suspense 폴백에 같은 행 컴포넌트를 세운다(회귀 이력이 있다).
   */
  let interactive = $state(false);
  onMount(() => {
    interactive = true;
  });

  const header = css({
    mb: '[30px]',
    pb: '[16px]',
    borderBottomWidth: '[1px]',
    borderBottomStyle: 'solid',
    borderColor: 'ink.border',
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '[16px]',
    flexWrap: 'wrap',
  });

  const heading = css({
    fontSize: '[21px]',
    fontWeight: 'bold',
    color: 'ink.950',
  });

  const count = css({
    fontFamily: 'mono',
    fontWeight: 'normal',
    fontSize: '[12px]',
    color: 'ink.500',
    fontVariantNumeric: 'tabular-nums',
  });
</script>

<Seo
  title={`글 | ${data.site.name}`}
  {description}
  canonical={`${data.site.url}${data.paths.posts}`}
  ogImage={`${data.site.url}${data.site.ogDefaultImage}`}
  siteName={data.site.name}
/>

<Rail width="wide" class={css({ py: { base: '10', md: '16' } })}>
  <!-- 허브 문법에 맞춘 헤더 — 큰 타이틀 대신 21px 산세리프 + 모노 수치 한 줄,
       구분은 hairline 보더 하나로만. -->
  <header class={header}>
    <h1 class={heading}>모든 노트</h1>
    <span class={count}>{data.posts.length}편</span>
  </header>

  {#if interactive}
    <PostsArchive
      posts={data.posts}
      seriesItems={data.seriesItems}
      tagItems={data.tagItems}
      yearItems={data.yearItems}
    />
  {:else}
    <ol class={css({ listStyleType: 'none', p: '0', m: '0' })}>
      {#each data.posts as post (post.slug)}
        <ArchiveRow
          href={post.href}
          title={post.title}
          dateLabel={post.dateLabel}
        />
      {/each}
    </ol>
  {/if}
</Rail>

// apps/blog/web/src/app/posts/page.tsx
import { Suspense } from 'react';
import { css, cx } from '@design-system/ui-lib/css';

import {
  getAllPostSummaries,
  getAllSeries,
  getAllTags,
  getAllYears,
} from '@/src/content';
import { safeJsonLd } from '@blog/content';
import { POSTS_TRANSITION_ID } from '@/src/shared/transitions';
import {
  buildBlogJsonLd,
  buildCollectionPageJsonLd,
  buildPostsMetadata,
} from './seo';
// 폴백 목록과 하이드레이션 후 목록이 같은 행 컴포넌트를 쓰도록 배럴(index.ts)이
// 아니라 모듈에서 직접 가져온다.
import {
  ArchiveRow,
  PostsArchiveView,
} from '@/src/components/blog/PostsArchive';
import { PageBoundary } from '@/src/components/PageBoundary';
import { railGutter, railColumn } from '@/src/components/Rail';

export const metadata = buildPostsMetadata();

// 글 목록에 기대지 않는 JSON-LD라 한 번만 만든다.
const blogJsonLd = buildBlogJsonLd();

export default function PostsPage() {
  // 로더 호출은 컴포넌트 안에 둔다. dev에서 `readAllPosts()`는 캐시를 건너뛰고
  // 매번 fs를 다시 읽는데(`repository.ts`), 그 설계는 요청마다 호출된다는
  // 전제 위에 있다 — 모듈 최상위로 올리면 dev 서버가 재시작 전까지 첫 요청
  // 시점 목록에 고정된다. draft·scheduled 글을 그대로 노출하는 목록이라
  // 글을 쓰는 동안 특히 크게 어긋난다.
  const posts = getAllPostSummaries();
  const series = getAllSeries();
  const tags = getAllTags();
  const years = getAllYears();
  const collectionPageJsonLd = buildCollectionPageJsonLd(posts);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(collectionPageJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(blogJsonLd) }}
      />
      <PageBoundary transitionId={POSTS_TRANSITION_ID} className={railGutter}>
        <div
          className={cx(
            railColumn({ width: 'wide' }),
            css({ py: { base: '10', md: '16' } }),
          )}
        >
          {/* 허브 문법에 맞춘 헤더 — 큰 세리프 타이틀 대신 21px 산세리프 +
              모노 수치 한 줄, 구분은 hairline 보더 하나로만. */}
          <header
            className={css({
              mb: '[30px]',
              pb: '[16px]',
              borderBottomWidth: '[1px]',
              borderBottomStyle: 'solid',
              borderColor: 'ink.border',
              display: 'flex',
              alignItems: 'baseline',
              justifyContent: 'space-between',
              gap: '[16px]',
              flexWrap: 'wrap',
            })}
          >
            <h1
              className={css({
                fontSize: '[21px]',
                fontWeight: 'bold',
                color: 'ink.950',
              })}
            >
              모든 노트
            </h1>
            <span
              className={css({
                fontFamily: 'mono',
                fontWeight: 'normal',
                fontSize: '[12px]',
                color: 'ink.500',
                fontVariantNumeric: 'tabular-nums',
              })}
            >
              {posts.length}편
            </span>
          </header>

          {/*
            PostsArchiveView는 nuqs(useSearchParams)를 쓰므로 output: 'export'의
            빌드 타임 프리렌더 대상에서 빠진다 (BAILOUT_TO_CLIENT_SIDE_RENDERING).
            즉 out/posts/index.html에 구워지는 건 아래 fallback이 전부다.
            스피너를 두면 아카이브 허브의 내부 링크가 0개가 되므로, 글 목록을 여기서
            프리렌더해 링크를 남긴다. (브라우저에서 하이드레이션되면 인터랙티브 뷰로 교체)
            회귀 이력: c206b99에서 도입 → 15ed918(리디자인)에서 유실 → 재도입.
          */}
          <Suspense
            fallback={
              <ol className={css({ listStyleType: 'none', p: '0', m: '0' })}>
                {posts.map(post => (
                  <ArchiveRow key={post.slug} post={post} />
                ))}
              </ol>
            }
          >
            <PostsArchiveView
              posts={posts}
              series={series}
              tags={tags}
              years={years}
            />
          </Suspense>
        </div>
      </PageBoundary>
    </>
  );
}
