// apps/blog/web/src/components/mobile/BackToTop.tsx
'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowUp } from 'lucide-react';
import { css } from '@design-system/ui-lib/css';

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth',
  });
};

export const BackToTop = () => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const toggleVisibility = () => setIsVisible(window.scrollY > 300);
    window.addEventListener('scroll', toggleVisibility);
    return () => window.removeEventListener('scroll', toggleVisibility);
  }, []);

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.button
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.8 }}
          onClick={scrollToTop}
          // MobileTOC와 같은 이유 — 아이콘 단독 버튼이라 이름이 필요하다.
          // 스크롤 전에는 렌더되지 않아 axe 스캔에 안 잡혔을 뿐, 같은 결함이다.
          aria-label="맨 위로 이동"
          whileTap={{ scale: 0.9 }}
          className={css({
            pos: 'fixed',
            bottom: '6',
            right: '6',
            w: '12',
            h: '12',
            bg: 'paper.100',
            rounded: 'full',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'ink.900',
            // 떠 있는 버튼이지만 그림자 대신 hairline 보더로 본문과 분리한다.
            borderWidth: 'hairline',
            borderColor: 'ink.borderStrong',
            cursor: 'pointer',
            zIndex: '40',
            _hover: { color: 'accent.600', borderColor: 'accent.200' },
          })}
        >
          <ArrowUp size={24} />
        </motion.button>
      )}
    </AnimatePresence>
  );
};

// apps/blog/web-svelte/src/lib/client/BackToTop.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { scale } from 'svelte/transition';
  import { css } from '../../../styled-system/css';

  /**
   * 맨 위로. `apps/blog/web/src/components/mobile/BackToTop.tsx`의 이식이다.
   * 300px 넘게 내려가면 나타난다.
   *
   * React 판은 motion으로 스케일 인/아웃 한다. 여기서는 svelte/transition의
   * `scale`이 같은 일을 한다.
   */
  const THRESHOLD = 300;

  let visible = $state(false);

  onMount(() => {
    const update = () => {
      visible = window.scrollY > THRESHOLD;
    };
    update();
    window.addEventListener('scroll', update, { passive: true });
    return () => {
      window.removeEventListener('scroll', update);
    };
  });

  const button = css({
    pos: 'fixed',
    bottom: '6',
    right: '6',
    w: '12',
    h: '12',
    bg: 'paper.100',
    rounded: 'full',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'ink.900',
    // 떠 있는 버튼이지만 그림자 대신 hairline 보더로 본문과 분리한다.
    borderWidth: 'hairline',
    borderColor: 'ink.borderStrong',
    cursor: 'pointer',
    zIndex: '[40]',
    _hover: { color: 'accent.600', borderColor: 'accent.200' },
  });

  const icon = css({ w: '[24px]', h: '[24px]' });
</script>

{#if visible}
  <button
    type="button"
    onclick={() => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }}
    transition:scale={{ duration: 200, start: 0.8 }}
    aria-label="맨 위로 이동"
    class={button}
  >
    <!-- lucide `arrow-up`과 같은 path다. -->
    <svg
      class={icon}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  </button>
{/if}
