// apps/blog/web-svelte/src/lib/components/Hero.svelte
<script lang="ts">
  import { css } from '../../../styled-system/css';
  import { RSS_PATH } from '@blog/content/client';
  import { AUTHOR_GITHUB } from '@blog/site-values';

  /** 히어로 pill — 이름 아래 외부 채널. */
  const pill = css({
    fontFamily: 'mono',
    fontWeight: 'normal',
    fontSize: '[12px]',
    color: 'ink.600',
    textDecoration: 'none',
    borderWidth: 'hairline',
    borderStyle: 'solid',
    borderColor: 'ink.border',
    rounded: 'pill',
    px: '[11px]',
    py: '[3px]',
    transition: '[color 0.15s, border-color 0.15s]',
    _hover: { color: 'ink.950', borderColor: 'ink.borderStrong' },
  });

  // RSS는 같은 도메인의 정적 파일이라 새 탭으로 열지 않는다.
  const PILLS = [
    { href: AUTHOR_GITHUB, label: 'github', external: true },
    { href: RSS_PATH, label: 'rss', external: false },
  ] as const;
</script>

<!-- <header>로 감싸면 브라우저가 main 안에서도 banner 랜드마크로 노출해 사이트
     헤더와 banner가 둘이 된다(axe: no-duplicate-banner). 그냥 div. -->
<div class={css({ mb: '[30px]' })}>
  <h1
    class={css({
      fontSize: '[21px]',
      fontWeight: 'bold',
      // 페이지 최상위 제목에만 액센트를 준다. 아래 소개 문단과 pill, 섹션
      // 라벨은 전부 무채색으로 남아야 "제목 > 그 외" 위계가 색으로 읽힌다.
      color: 'accent.900',
      mb: '[8px]',
    })}
  >
    한상욱
  </h1>
  <p class={css({ fontSize: '[14px]', color: 'ink.600' })}>
    구조를 그려서 문제를 푸는 프론트엔드 엔지니어.
    <br />
    디자인 시스템, 모노레포, 배포 파이프라인을 다룹니다.
  </p>
  <div
    class={css({ display: 'flex', flexWrap: 'wrap', gap: '[8px]', mt: '[14px]' })}
  >
    {#each PILLS as item (item.label)}
      <a
        href={item.href}
        target={item.external ? '_blank' : undefined}
        rel={item.external ? 'noopener noreferrer' : undefined}
        class={pill}>{item.label}</a
      >
    {/each}
  </div>
</div>

// apps/blog/web/src/components/blog/Hero.tsx
import { RSS_PATH } from '@blog/content';
import { AUTHOR_GITHUB } from '@/content.values.mts';
import { css } from '@design-system/ui-lib/css';

/** 히어로 pill — 이름 아래 외부 채널. 레퍼런스 `.pill` 수치 그대로. */
const pill = css({
  fontFamily: 'mono',
  fontWeight: 'normal',
  fontSize: '[12px]',
  color: 'ink.600',
  borderWidth: 'hairline',
  borderStyle: 'solid',
  borderColor: 'ink.border',
  rounded: 'pill',
  px: '[11px]',
  py: '[3px]',
  transition: '[color 0.15s, border-color 0.15s]',
  _hover: { color: 'ink.950', borderColor: 'ink.borderStrong' },
});

// 레퍼런스에는 velog pill도 있지만 크로스포스팅을 접기로 해서 뺐다.
const PILLS = [
  { href: AUTHOR_GITHUB, label: 'github', external: true },
  // RSS는 같은 도메인의 정적 파일이라 새 탭으로 열지 않는다.
  { href: RSS_PATH, label: 'rss', external: false },
] as const;

export const Hero = () => {
  return (
    // <header>로 감싸면 Chrome이 main 안에서도 banner 랜드마크로 노출해
    // 사이트 헤더와 banner가 둘이 된다(axe: no-duplicate-banner). 그냥 div.
    //
    // 레퍼런스는 우측 210px에 장식 다이어그램 모티프를 뒀지만 걷어냈다.
    // `aria-hidden` 장식이라 정보가 0인데, 정작 다이어그램이 의미를 갖는 자리
    // (글 히어로·본문)와 언어가 겹쳐 그쪽 무게를 깎았다. 다이어그램은 글 안에서만
    // 쓴다.
    <div className={css({ mb: '[30px]' })}>
      <h1
        className={css({
          fontSize: '[21px]',
          fontWeight: 'bold',
          // 페이지의 최상위 제목이라 액센트를 준다. 아래 소개 문단과 pill,
          // 섹션 라벨은 전부 무채색으로 남는다 — 액센트가 제목 계열에만
          // 붙어야 "제목 > 그 외"라는 위계가 색으로 읽힌다.
          color: 'accent.900',
          mb: '[8px]',
        })}
      >
        한상욱
      </h1>
      <p className={css({ fontSize: '[14px]', color: 'ink.600' })}>
        구조를 그려서 문제를 푸는 프론트엔드 엔지니어.
        <br />
        디자인 시스템, 모노레포, 배포 파이프라인을 다룹니다.
      </p>
      <div
        className={css({
          display: 'flex',
          flexWrap: 'wrap',
          gap: '[8px]',
          mt: '[14px]',
        })}
      >
        {PILLS.map(item => (
          <a
            key={item.label}
            href={item.href}
            target={item.external ? '_blank' : undefined}
            rel={item.external ? 'noopener noreferrer' : undefined}
            className={pill}
          >
            {item.label}
          </a>
        ))}
      </div>
    </div>
  );
};
