// apps/blog/web-svelte/src/lib/components/archive/PostsFilterSheet.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { css } from '../../../../styled-system/css';

  /**
   * 모바일 `/posts` 전용 필터 바텀시트.
   * `apps/blog/web/src/components/blog/PostsFilterSheet.tsx`의 이식이다.
   *
   * 내용은 호출부가 snippet으로 주입한다 — 데스크톱 사이드바와 **같은**
   * `PostsFilterPanel`이 여기 들어온다.
   *
   * React 판은 `Portal`로 DOM 밖에 낸다. 여기서는 그럴 필요가 없다: 이 컴포넌트는
   * 아카이브 그리드의 형제로 서고, 그 위에 쌓임 맥락을 만드는 조상이 없다.
   */
  const {
    open,
    onClose,
    onClearAll,
    activeCount,
    children,
  }: {
    open: boolean;
    onClose: () => void;
    onClearAll: () => void;
    activeCount: number;
    children: Snippet;
  } = $props();

  let sheet = $state<HTMLDivElement>();

  const FOCUSABLE =
    'a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])';

  function focusables(): HTMLElement[] {
    if (!sheet) return [];
    return Array.from(sheet.querySelectorAll<HTMLElement>(FOCUSABLE)).filter(
      el => !el.hasAttribute('disabled'),
    );
  }

  /** Escape로 닫고, Tab을 시트 안에 묶는다(포커스 트랩). */
  function onKeydown(event: KeyboardEvent) {
    if (!open) return;
    if (event.key === 'Escape') {
      event.stopPropagation();
      onClose();
      return;
    }
    if (event.key !== 'Tab') return;
    const items = focusables();
    const first = items.at(0);
    const last = items.at(-1);
    if (first === undefined || last === undefined) return;
    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  }

  $effect(() => {
    if (!open) return;
    // 시트 뒤가 스크롤되면 닫았을 때 읽던 자리를 잃는다(SearchDialog와 같은 규칙).
    document.body.style.overflow = 'hidden';
    // 열기 전 포커스를 기억해 두었다가 닫을 때 되돌린다. activeElement는
    // Element라 focus()가 없는 것(SVG 등)도 오므로 되돌릴 수 있는 것만 든다.
    const previous =
      document.activeElement instanceof HTMLElement
        ? document.activeElement
        : null;
    const frame = requestAnimationFrame(() => focusables().at(0)?.focus());
    return () => {
      cancelAnimationFrame(frame);
      document.body.style.removeProperty('overflow');
      previous?.focus();
    };
  });

  const backdrop = css({
    pos: 'fixed',
    inset: '0',
    bg: '[rgba(1,4,9,0.8)]',
    zIndex: '[50]',
  });

  const panel = css({
    pos: 'fixed',
    bottom: '0',
    left: '0',
    right: '0',
    bg: 'paper.100',
    borderTopWidth: '[1px]',
    borderRightWidth: '[1px]',
    borderLeftWidth: '[1px]',
    borderStyle: 'solid',
    borderColor: 'ink.border',
    zIndex: '[51]',
    roundedTop: '[12px]',
    maxH: '[85vh]',
    display: 'flex',
    flexDir: 'column',
    paddingBottom: '[env(safe-area-inset-bottom)]',
  });

  const grabberRow = css({
    display: 'flex',
    justifyContent: 'center',
    pt: '[8px]',
    pb: '[4px]',
  });

  const grabber = css({
    width: '[32px]',
    height: '[4px]',
    rounded: '[2rem]',
    bg: 'ink.border',
  });

  const header = css({
    px: '[16px]',
    py: '[12px]',
    borderBottomWidth: '[1px]',
    borderBottomStyle: 'solid',
    borderColor: 'ink.border',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  });

  const headerTitle = css({
    fontSize: '[16px]',
    fontWeight: 'semibold',
    color: 'ink.950',
  });

  const clearAllButton = css({
    bg: 'paper.200',
    borderWidth: '[1px]',
    borderStyle: 'solid',
    borderColor: 'ink.border',
    rounded: '[6px]',
    px: '[16px]',
    py: '[5px]',
    color: 'ink.800',
    fontSize: 'sm',
    fontWeight: 'medium',
    cursor: 'pointer',
    _hover: { bg: 'paper.300', borderColor: 'ink.borderStrong' },
  });

  const body = css({
    px: '[16px]',
    py: '[16px]',
    overflowY: 'auto',
    flex: '1',
    display: 'flex',
    flexDir: 'column',
    gap: '[16px]',
  });

  const closeIcon = css({ w: '[20px]', h: '[20px]' });
</script>

<svelte:window onkeydown={onKeydown} />

{#if open}
  <!-- dim 레이어를 눌러 닫는 것은 포인터 편의일 뿐이고, 키보드로 닫는 길은
       위 Escape와 아래 닫기 버튼이다(SearchDialog와 같은 처리). -->
  <div
    role="presentation"
    class={backdrop}
    onclick={onClose}
    transition:fade={{ duration: 200 }}
  ></div>

  <div
    bind:this={sheet}
    role="dialog"
    aria-modal="true"
    aria-label="글 필터"
    class={panel}
    transition:fly={{ y: 400, duration: 280 }}
  >
    <div class={grabberRow}>
      <span class={grabber}></span>
    </div>
    <div class={header}>
      <h2 class={headerTitle}>
        {activeCount > 0 ? `필터 · ${activeCount}` : '필터'}
      </h2>
      <div class={css({ display: 'flex', gap: '[8px]', alignItems: 'center' })}>
        {#if activeCount > 0}
          <button
            type="button"
            onclick={() => {
              onClearAll();
              onClose();
            }}
            class={clearAllButton}
          >
            모두 지우기
          </button>
        {/if}
        <button
          type="button"
          onclick={onClose}
          aria-label="닫기"
          class={css({ cursor: 'pointer', color: 'ink.600' })}
        >
          <!-- lucide `x`와 같은 path다. -->
          <svg
            class={closeIcon}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path d="M18 6 6 18" />
            <path d="m6 6 12 12" />
          </svg>
        </button>
      </div>
    </div>
    <div class={body}>
      {@render children()}
    </div>
  </div>
{/if}

// apps/blog/web/src/components/blog/PostsFilterSheet.tsx
'use client';

import { useEffect, useRef, type ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X } from 'lucide-react';
import { css } from '@design-system/ui-lib/css';
import { Portal } from '@/src/components/Portal';

interface PostsFilterSheetProps {
  open: boolean;
  onClose: () => void;
  onClearAll: () => void;
  activeCount: number;
  children: ReactNode;
}

/**
 * 모바일 /posts 페이지 전용 필터 바텀시트.
 * MobileTOC과 동일한 motion 기반 슬라이드 업 패턴이며, 내용은 호출 측이
 * children으로 주입합니다 (정렬·뷰토글·태그·시리즈·연도 등).
 */
export const PostsFilterSheet = ({
  open,
  onClose,
  onClearAll,
  activeCount,
  children,
}: PostsFilterSheetProps) => {
  const sheetRef = useRef<HTMLDivElement | null>(null);
  const previouslyFocusedRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    // Escape로 닫기 + Tab을 시트 내부로 묶어 포커스 트랩.
    const focusableSelector =
      'a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])';
    previouslyFocusedRef.current = document.activeElement as HTMLElement | null;
    // 다음 frame에 시트가 마운트된 후 첫 focusable로 포커스를 옮깁니다.
    const focusFirst = requestAnimationFrame(() => {
      const first =
        sheetRef.current?.querySelector<HTMLElement>(focusableSelector);
      first?.focus();
    });
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        onClose();
        return;
      }
      if (e.key !== 'Tab') return;
      const root = sheetRef.current;
      if (!root) return;
      const focusables = Array.from(
        root.querySelectorAll<HTMLElement>(focusableSelector),
      ).filter(el => !el.hasAttribute('disabled'));
      if (focusables.length === 0) return;
      const first = focusables[0];
      const last = focusables[focusables.length - 1];
      const active = document.activeElement;
      if (e.shiftKey && active === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && active === last) {
        e.preventDefault();
        first.focus();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => {
      cancelAnimationFrame(focusFirst);
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
      previouslyFocusedRef.current?.focus();
    };
  }, [open, onClose]);

  return (
    <Portal>
      <AnimatePresence>
        {open && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={onClose}
              className={css({
                pos: 'fixed',
                inset: '0',
                bg: '[rgba(1,4,9,0.8)]',
                zIndex: '50',
              })}
            />
            <motion.div
              ref={sheetRef}
              role="dialog"
              aria-modal="true"
              aria-label="글 필터"
              initial={{ y: '100%' }}
              animate={{ y: 0 }}
              exit={{ y: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className={css({
                pos: 'fixed',
                bottom: '0',
                left: '0',
                right: '0',
                bg: 'paper.100',
                borderTopWidth: '[1px]',
                borderRightWidth: '[1px]',
                borderLeftWidth: '[1px]',
                borderStyle: 'solid',
                borderColor: 'ink.border',
                zIndex: '51',
                roundedTop: '[12px]',
                maxH: '[85vh]',
                display: 'flex',
                flexDir: 'column',
                paddingBottom: '[env(safe-area-inset-bottom)]',
              })}
            >
              <div
                className={css({
                  display: 'flex',
                  justifyContent: 'center',
                  pt: '[8px]',
                  pb: '[4px]',
                })}
              >
                <span
                  className={css({
                    width: '[32px]',
                    height: '[4px]',
                    rounded: '[2rem]',
                    bg: 'ink.border',
                  })}
                />
              </div>
              <div
                className={css({
                  px: '[16px]',
                  py: '[12px]',
                  borderBottomWidth: '[1px]',
                  borderBottomStyle: 'solid',
                  borderColor: 'ink.border',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                })}
              >
                <h2
                  className={css({
                    fontSize: '[16px]',
                    fontWeight: 'semibold',
                    color: 'ink.950',
                  })}
                >
                  필터{activeCount > 0 ? ` · ${activeCount}` : ''}
                </h2>
                <div
                  className={css({
                    display: 'flex',
                    gap: '[8px]',
                    alignItems: 'center',
                  })}
                >
                  {activeCount > 0 && (
                    <button
                      type="button"
                      onClick={() => {
                        onClearAll();
                        onClose();
                      }}
                      className={css({
                        bg: 'paper.200',
                        borderWidth: '[1px]',
                        borderStyle: 'solid',
                        borderColor: 'ink.border',
                        rounded: '[6px]',
                        px: '[16px]',
                        py: '[5px]',
                        color: 'ink.800',
                        fontSize: 'sm',
                        fontWeight: 'medium',
                        cursor: 'pointer',
                        _hover: {
                          bg: 'paper.300',
                          borderColor: 'ink.borderStrong',
                        },
                      })}
                    >
                      모두 지우기
                    </button>
                  )}
                  <button
                    type="button"
                    onClick={onClose}
                    aria-label="닫기"
                    className={css({ cursor: 'pointer', color: 'ink.600' })}
                  >
                    <X size={20} />
                  </button>
                </div>
              </div>
              <div
                className={css({
                  px: '[16px]',
                  py: '[16px]',
                  overflowY: 'auto',
                  flex: '1',
                  display: 'flex',
                  flexDir: 'column',
                  gap: '[16px]',
                })}
              >
                {children}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </Portal>
  );
};
